openapi: 3.1.0
info:
  title: Fee Collection Service API
  version: 1.0.0
paths:
  /students:
    post:
      summary: Create a new payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeePayment'
      responses:
        '201':
          description: Student payment created
  /students/{studentId}:
    get:
      summary: Get student by Student ID
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: long
      responses:
        '200':
          description: Student details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
components:
  schemas:
    Student:
      type: object
      properties:
        studentId:
          type: integer
        studentName:
          type: string
        grade:
          type: string
        mobileNumber:
          type: string
        schoolName:
          type: string