spring:
  datasource:
    url: jdbc:h2:mem:student-manager
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 200
      minimum-idle: 50
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  profiles:
    active: dev

  application:
    name: fee-service

server:
  port: 8081
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: 200
      min-spare: 50